language: node_js
node_js:
- '10'
script:
  - npm run build
deploy:
  - provider: cloudfoundry
    edge: true
    username: pivotal@farkas.land
    password:
      secure: euFzEsaF/pdILbWF9ypfhdXHT4d/1pY1RtcWb0Vt6FKv5UJZgg+0/ILCRqFq3YBumBSLzqqOQLOFis1Kr5zj7Vu/LZvCKHlRodWROq9EVkEZNp0hpWdCbysN46wEETby7pXmLEm9VdmrYCJd8QUxJYalpKPQ7P77YFfAp0FrCoiYAbD3x6QhKDmpvvdxav0x8zSJI3ZdaxF9G9S4S2NVM7N72sT/AoqQeMztV4LucFc6n3EuOHV+7XqoAuqkXbZDO18K7U8LrYGlmkHvAT0d1oKNLXB5H210perQgD25R/csUHCUSg2Uyz2GW4KFHXgqai+0gz3KQpe3UqXmh+2J8eF5+nH0zyXo3thjtYp1O+kfeAkP/ti3Hp00sEHj3bYarMiCL56S6efACdxb16zkcPmgpJP+12A7rOtEz1NSKHeWEZutnp81UKxQQlDHuLGvggIrnOtV5+xmfsN7M9/bWqlaOFtkSAPslg4MTqJoruXluFMN/kIWFDYTwfUqtQXQblxQt5I9hxezp1OktmgQwEAdMVphzVtZjiHb+Fla2EKfDnvP4Ye8rwtEtnqIbtNP++3nD3QydGBucRsCa/CCV3Cn2NeLrH/ZnDuA7sEhlnLd+J86rxsDKdBnHD6LaZMugMz1uqe9pw/L2RyA+sHCW85YpvBdiR2XigrxlGO/A1c=
    api: https://api.run.pivotal.io
    organization: farkas-land
    space: development
